receivers:
  otlp:
    protocols:
      grpc:
      http:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'ray'
          scrape_interval: 10s
          static_configs:
            - targets:
                - 'ray-head:8267'
          metrics_path: /metrics

processors:
  batch:
  memory_limiter:
    limit_mib: 4000
    spike_limit_mib: 500
    check_interval: 5s

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [prometheus, otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheusremotewrite, logging]

