global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ray'
    static_configs:
      - targets: ['ray-head:8267']
    metrics_path: /metrics

remote_write:
  - url: "http://prometheus:9090/api/v1/write"
