model_import_path: src.ray.deployments.model:app
request_import_path: src.ray.deployments.request:app
request_num_replicas: 1
models:

  - model_key: 'google/gemma-7b'
    cuda_memory_MB: 70000.0
    num_replicas: 1

  - model_key: 'EleutherAI/gpt-j-6b'
    cuda_memory_MB: 60000.0
    num_replicas: 1

  - model_key: 'meta-llama/Meta-Llama-3-8B'
    cuda_memory_MB: 80000.0
    num_replicas: 2

  # - model_key: 'meta-llama/Meta-Llama-3-70B'
  #   cuda_memory_MB: 700000.0
  #   num_replicas: 1
