channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - pip
    - setuptools
    # API
    - fastapi-cache2
    - fastapi==0.108.0
    - fastapi-socketio
    - python-socketio
    - aio_pika
    - firebase-admin
    # Telemetry
    - asgiref
    - opentelemetry-api
    - opentelemetry-sdk
    - opentelemetry-exporter-otlp
    - opentelemetry-instrumentation-fastapi
    # Http server
    - uvicorn[standard]==0.24.0
    - gunicorn
    - eventlet
    # Database
    - pymongo
    # Tasks
    - ray[serve]
    - requests
    - torch
    - git+https://github.com/ndif-team/nnsight@0.3
