version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - prometheus-data:/prometheus
      - ../../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - api
      - ray-head

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp # Accept `jaeger.thrift` over Thrift-compact protocol
      - 16686:16686 # Serve Jaeger web UI

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - jaeger
      - prometheus

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  ray-head:
    image: ray_head:latest
    shm_size: '2gb'
    ports:
      - 8265:8265 # Dashboard 
      - 8267:8267 # Metrics export port
    volumes:
      - /disk/u/mripa/.cache/huggingface/hub/:/root/.cache/huggingface/hub
      - ray-data:/tmp/ray/session_latest
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    environment:
       - RAY_METRICS_EXPORT_PORT=8267
       - RAY_JOB_METRICS_EXPORT_PORT=8267
       - RAY_METRICS_GAUGE_EXPORT_INTERVAL_MS=1000

  api:
    depends_on:
      - jaeger
      - rabbitmq
      - ray-head
      - mongodb
    image: api:latest
    ports:
      - 5001:80
    environment:
      DATABASE_URL: mongodb://user:pass@mongodb:27017
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
      WORKERS: 1
      RAY_ADDRESS: ray://ray-head:10001
      # FIREBASE_CREDS_PATH


volumes:
  grafana-storage:
  prometheus-data:
  ray-data:
