version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.11.28
    network_mode: "host"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  ray-head:
    image: ray_head:latest
    shm_size: '12gb'
    network_mode: "host"
    volumes:
      - /home/ubuntu/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - ray-data:/tmp/ray/session_latest
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
       - RAY_METRICS_EXPORT_PORT=8267
       - RAY_JOB_METRICS_EXPORT_PORT=8267
       - RAY_METRICS_GAUGE_EXPORT_INTERVAL_MS=1000
       - HF_TOKEN="add hf token"

  api:
    depends_on:
      - rabbitmq
      - ray-head
      - mongodb
    image: api:latest
    network_mode: "host"
    environment:
      DATABASE_URL: mongodb://user:pass@localhost:27017
      RMQ_URL: amqp://guest:guest@localhost:5672/
      WORKERS: 1
      RAY_ADDRESS: ray://localhost:10001
      # FIREBASE_CREDS_PATH
      HF_TOKEN: "add hf token"

  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - prometheus-data:/prometheus
      - ../../telemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
      - ray-head

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  prometheus-data:
  ray-data:
