version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.11.28
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  ray-head:
    image: ray_head:latest
    shm_size: '2gb'
    ports:
      # Dashboard 
      - 8266:8265
    volumes:
      - /disk/u/mripa/.cache/huggingface/hub/:/root/.cache/huggingface/hub
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  api:
    depends_on:
      - rabbitmq
      - ray-head
      - mongodb
    image: api:latest
    ports:
      - 5001:80
    environment:
      DATABASE_URL: mongodb://user:pass@mongodb:27017
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
      WORKERS: 1
      RAY_ADDRESS: ray://ray-head:10001
      # FIREBASE_CREDS_PATH
